# RuboCop configuration
plugins:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'ext/**/target/**'
    - 'ext/**/Cargo.lock'
    - 'ext/**/build.rs'
    - 'ext/**/src/**'
    - 'vendor/**/*'
    - 'bin/*' # for now

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'bin/**/*'

RSpec:
  Enabled: true
