[package]
name = "fastsheet"
version = "0.1.0"
publish = false
build = "build.rs"
edition = "2021"

[lib]
name = "fastsheet"
crate-type = ["cdylib"]

[dependencies]
calamine = { version = "0.30.1", features = ["dates"] }
libc = "0.2"

[build-dependencies]
cc = "1.0"
