name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: "development"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ext/fastsheet/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('ext/fastsheet/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install gems
        run: bundle install --jobs 4 --retry 3

      - name: Show versions
        run: |
          ruby -v
          bundle -v
          cargo -V
          rustc -V

      - name: Lint
        run: bundle exec rake lint

      - name: Test
        run: bundle exec rake test

